demo/demo-job.xml
demo/demo.sh

This PR contains a demo job (in Jenkins XML) that sleeps for five minutes. It also includes a script to create 50 of these sleep jobs, and optionally clean them up when you're done.

Demo job and script

---

.dockerignore
.gitignore
tests/acceptance/fixtures/test-job.xml
tests/acceptance/requirements.txt
tests/acceptance/test_jenkins.py

Add acceptance tests to the project.

Acceptance Tests

---

Dockerfile
README.md

Update Jenkins version to version 1.642.4.

Update Jenkins LTS

---

tests/acceptance/test_jenkins.py

This PR breaks testing up into smaller steps, as well as uses some
required new Shakedown functions (such as `http()` for authenticated
HTTP requests).

Improve jenkins-mesos acceptance testing

---

docs/README.md
docs/_config.yml
docs/_layouts/default.html
docs/docs/builds.md
docs/docs/configuration.md
docs/docs/contributing.md
docs/docs/index.md
docs/docs/upgrading.md
docs/index.md
docs/support.md

This PR renames occurrences of `Mesos` to `DC/OS` now that the
repository has been renamed.

(docs) renaming occurrences of 'Mesos' to 'DC/OS'

---

.gitignore
Dockerfile
README.md
pom.xml
scripts/plugin-list.py

Integrate Jenkins 2.7.1 LTS (jenkins-dcos v2.0.0)

---

pom.xml

Roll version to next dev release version.

Prepare Next Dev Version

---

README.md
pom.xml

Add the gitlab plugin to the plugins that are packaged with jenkins-dcos.

Add GitLab Plugin

---

CHANGELOG.md
pom.xml

Release 2.0.1-2.7.4

---

README.md
pom.xml

- Upgrade Jenkins to 2.19.1 LTS
- Add several new Blue Ocean plugins
- Upgrade all plugins to the latest versions
- git and git-client were not bumped to new major version

Update Jenkins and Plugins to Latest

---

CHANGELOG.md
README.md

Updates to README and CHANGELOG files for next release.

Changelog for 3.0.0

---

Dockerfile
README.md

Add more plugins to be versioned.

Track more plugins

---

Dockerfile
README.md

Add more versioned plugins to the list of prepackaged plugins.

More Plugins to Track

---

Dockerfile
README.md
conf/jenkins/config.xml
scripts/dcos-account.sh

Updated:
- Jenkins to 2.32.3
- mesos plugin to 0.14.1
- ssh plugin to 1.14
Added an additional script that writes credentials to file instead of remaining in environment variables.

Update Versions and Environment Vars

---

CHANGELOG.md
Dockerfile
README.md
scripts/test.sh

* Upgrades Jenkins to 2.46.2 LTS
* Updates various plugins to their latest versions

V3.1.0-2.46.2

---

Dockerfile

- Updates Jenkins to 2.60.2 LTS version
- Updates plugins to latest versions
- Adds new Azure plugin

Jenkins LTS 2.60.2

---

Dockerfile
README.md

Update link to getting started docs

Update jenkins plugins and base image in Dockerfile

---

Dockerfile
README.md

Updated Blueocean editor version to 1.2.4 & changed README file.

Updated the Blueocean editor version.

---

Dockerfile
scripts/dcos-pem.sh
tests/scripts/create-pem-secret.sh
tests/scripts/get-pem.sh
tests/scripts/marathon.json

Will clean this up when working... checkin point for other users.

Add secret pem keystore

---

Dockerfile

Updating libmesos version in dockerfile

Updating to the latest libmesos version

---

tools/dashboards/DC-OS.json
tools/dashboards/JenkinsService.json
tools/dashboards/Mesos.json
tools/dashboards/SDK.json

Copied over from https://github.com/mesosphere/prometheus/tree/master/dashboards
We can add more as needed.

Add  dashboards

---

Dockerfile

This adds the start of the statsd exporter plugin to our image. Needs future work to rename all graphite references to statsd.

Added initial work of statsd exporter plugin.

---

testing/jenkins_remote_access.py
tests/scale/test_scale_utils.py

TODO: use this utility to list errors across all running jenkins services and take the top n

Adding utility to count and list job errors for a given jenkins instance

---

testing/jenkins.py
testing/jenkins_remote_access.py
testing/sdk_dcos.py
tests/scale/test_load.py
tests/scale/test_scale_utils.py

Launch Jenkins instances on strict mode cluster with auto-security mode detection.

Strict mode

---

tools/dashboards/Jenkins_Jobs.json

Adding a few more graphs on executor provision time

Adding more panels on executor provision time

---

testing/jenkins.py
tests/scale/test_load.py

The seed job will now retry over and over again.

Fix Jenkins tests to retry.

---

scripts/bootstrap.py

Already merged into 3.5.x branch, just including in master too now.
https://jira.mesosphere.com/browse/DCOS_OSS-4006

Fixing Mesos DNS name handling in master.
