mesosphere/dcos-jenkins-service

- Dockerfile
- README.md
This bumps Jenkins to the latest LTS release which includes a patch to mitigate the recently announced zero-day vulnerability. (See: https://jenkins-ci.org/content/mitigating-unauthenticated-remote-code-execution-0-day-jenkins-cli)
> Bump Jenkins to latest long term support version.

- conf/jenkins/config.xml
Prior to this commit, Jenkins connected to `master.mesos:5050` which is
fine for single-master deployments. When you're running Mesos in a HA
deployment (3 or 5 masters), this could result in Jenkins attempting to
register with a non-leader. Jenkins will work fine, but the framework
won't be registered to the cluster, and it won't appear in the Mesos UI.
This commit modifies the master hostname/IP address from
`master.mesos:5050` to `leader.mesos:5050`. If the leader should change,
Mesos-DNS will update this record, and Jenkins will connect to the
current leader.
> connect to leader.mesos in HA deployments

- conf/jenkins/config.xml
Prior to this commit, we used the openjdk-8-jre image by default, which
didn't include Git. The JDK image includes Git.
> use the java:openjdk-8-jdk image by default

- README.md
- scripts/plugin_install.sh
The AnsiColor plugin adds support for ANSI escape sequences, most
notably color, to the Console Output for a particular build. This should
improve the readability and user experience when viewing console logs
via the Jenkins web UI, but won't affect the "plain text" console logs.
> install the ansicolor plugin

- dind-agent/Dockerfile
- scripts/bootstrap.py
This PR introduces the ability to add the public keys for known SSH hosts.
* On the Jenkins master, this is accomplished by passing a space-separated string of hosts using the environment variable `SSH_KNOWN_HOSTS`. `ssh-keyscan` will gather the public keys for each of these hosts and write them to `/etc/ssh/ssh_known_hosts`.
* On our default dind-agent Docker image for Jenkins build agents, I've added github.com specifically to the Dockerfile. Users not using GitHub should either add additional well-known hosts to this list, or adapt this Docker image to their organization's needs.
> Populate SSH known_hosts file

- scripts/bootstrap.py
This commit removes the if-statement from `is_firstrun` and allows the
comparison to return directly.  main() now sets "firstrun" to the result
of "is_firstrun()", instead of a hard coded value of `True`, and sets
"jenkins_data_dir" accordingly.
> Improve code readability for bootstrap.py

- dind-agent/Dockerfile
In particular, git's submodule retrieval invokes perl
> Add perl: used by some git functionality

- conf/jenkins/config.xml
We ran into an issue where one of our DCOS agents was having trouble
communicating with the agent that the Jenkins scheduler was running on.
Because of the default reconnect behavior in Jenkins' slave.jar, this
meant that the Jenkins agent came up fine as a Mesos task, and got stuck
in an infinite loop attempting to connect to the Jenkins scheduler every
10 seconds.
This commit modifies the behavior of slave.jar to never attempt to
reconnect with a master on network failure. Not only will this prevent
any infinite loops from network issues, it will also ensure that if the
scheduler fails over and starts running with a different host/port
combination, that any running tasks will exit on their own instead of
running indefinitely.
> default jenkins agent should use -noReconnect

- dind-agent/README.md
- docs/docs/builds.md
This PR updates documentation for the jenkins-dind Docker image that we include in this repository. Specifically, it provides justification for using VFS, despite it (probably) being the slowest storage driver for Docker.
Also, this PR reformats the builds.md documentation for each line to be 80 characters long, for ease of maintenance going forward.
> Update documentation for jenkins-dind

- README.md
- scripts/plugin_install.sh
This new version includes a number of fixes, including support for Mesos 0.27.0: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jenkins-mesos/A_5JuE9eP0k/tnF9ey1IIAAJ
To be merged only once the Mesos plugin is available from the Jenkins Update Center: https://wiki.jenkins-ci.org/display/JENKINS/Mesos+Plugin
> Update Mesos plugin version.

- dind-agent/wrapper.sh
The docker engine that this image is running on in my system is using the overlay storage driver, and I noticed if I also use that driver performance is drastically improved.
I'm not sure what driver will be used if that option is removed completely, but it might be worth investigating.
> use overlay storage driver instead of vfs

- CHANGELOG.md
- README.md
- conf/jenkins/config.xml
- dind-agent/README.md
Prepare for the 0.2.2 release of jenkins-mesos, including changes to the dind-agent image and adding a changelog to the repo.
> jenkins-mesos 0.2.2 release

- README.md
- scripts/plugin_install.sh
The GitHub plugin depends on the github-api plugin, but prior to this
commit it wasn't installed. This commit adds the github-api plugin so
that Jenkins can successfully load the GitHub plugin.
> add github-api plugin

- README.md
This updates the build badge to our public Velocity jobs rather than
(outdated) TeamCity.
> Update build badge to Velocity

- tests/acceptance/requirements.txt
Shakedown provides a `http` object which overlays DC/OS authentication
on top of the `requests` library.
> The `requests` library is no longer a requirement

- conf/nginx/nginx.conf
Updated the maximum client body size configuration value to solve a 413 Request Entity Too Large Error in Nginx when uploading a plugin > 1MB.
> Updated maximum client body size

- Dockerfile
- README.md
This commit bumps Nginx from 1.9.9 to 1.10.1, the current stable
version.
> bump nginx to 1.10.1

- Dockerfile
Allow arbitrary options to be passed to Jenkins through the new JENKINS_OPTS environment variable. This behaves the same as JVM_OPTS.
> Add Jenkins Options

- scripts/bootstrap.py
Hello,
I tried to use the docker image and encountered the missing environment variable error. I think it would be better if we output explicitly the missing env variable name.
Thanks
> Add explicitly missing env variable name in bootstrap script

- README.md
- pom.xml
Upgrade Jenkins to LTS 2.19.3 due to security issue.
More information available from:
* https://jenkins.io/blog/2016/11/16/security-updates-addressing-zero-day/
* https://wiki.jenkins-ci.org/display/SECURITY/Jenkins+Security+Advisory+2016-11-16
* https://groups.google.com/forum/#!msg/jenkinsci-advisories/-fc-w9tNEJE/GRvEzWoJBgAJ
> Upgrade to 2.19.3 LTS

- Dockerfile
- scripts/export-libssl.sh
The passed in SSL paths are relative to the MESOS_SANDBOX for DC/OS 1.8
and below (fix intended for 1.9). This is not the directory where Jenkins
is executed from. This commit adds a script that transforms the relative
to absolute paths and allows Jenkins to start on a strict cluster.
> SSL Vars Should Be Absolute Paths

- conf/jenkins/config.xml
This changes the default remoteFSRoot for our default build agent to use the Mesos sandbox directory. Theoretically this should allow us to use the Mesos disk isolation, if enabled, when these agents run and use the sandbox viewer to see workspace files.
> Update remote FS root to use sandbox.

- Dockerfile
This solves a bug where the executor's LD_LIBRARY_PATH on DC/OS 1.8.8 would be improperly overwritten by the variable we had set in the marathon.json for Jenkins. This would cause Jenkins to fail to start on operating systems where libssl was not present in the system's PATH (e.g. CentOS but not CoreOS). 
See https://github.com/mesosphere/universe/pull/1041 for why this is no longer necessary. This PR adds the contents of that variable to the Docker CMD.
> Update Dockerfile CMD to include default paths for LD_LIBRARY_PATH.

- conf/nginx/nginx.conf
Updates to improve nginx proxy service reliability when dealing with Jenkins latency from any source (network/storage/etc...).
Based on recommendations here: https://wiki.jenkins-ci.org/display/JENKINS/Jenkins+behind+an+NGinX+reverse+proxy
Mitigator for https://github.com/mesosphere/dcos-jenkins-service/issues/127 -- but would be best done as DC/OS tunable parameters rather than hardcoded into nginx.conf imho.
> Update nginx.conf for tolerant proxy timeout

- Dockerfile
This change sets a default CSP value that the user can override. See discussion at https://jira.mesosphere.com/browse/QUALITY-1412 for more info.
Still todo: testing with possible CSP values, and updating Universe to accept this new parameter (and having it manage defaults properly)
> let users manage the Content Security Policy

- CHANGELOG.md
- Dockerfile
- README.md
v3.5.0-2.107.2 (2018-04-12)
* [Addresses security bulletin for 2018-04-11](https://jenkins.io/security/advisory/2018-04-11/)
* Updates blueocean to version [1.5.0](https://github.com/jenkinsci/blueocean-plugin/releases)
* Updates various plugins
* Remove [ace-editor](https://plugins.jenkins.io/ace-editor) & [momentjs](https://plugins.jenkins.io/momentjs) as they should not be installed directly
Issues still open
* [deprecated and unsecure JNLP1/JNLP2/JNLP3/CLI1/CLI2](https://issues.jenkins-ci.org/browse/JENKINS-45841) should be disabled by default
* [libmesos-bundle](https://github.com/mesosphere/dcos-jenkins-service/blob/master/Dockerfile#L13) should be upgraded from 1.8.7 to 1.11.0
* Disable Jenkins CLI to work in `-remoting mode` by default
> Upgraded jenkins to 2.107.2 to address security advisories

- conftest.py
- testing/jenkins.py
- testing/jenkins_remote_access.py
- testing/sdk_marathon.py
- testing/testData/gen-job.xml
- tests/scale/test_load.py
- tests/scale/test_scale_utils.py
Add a new mark (`scale`) that is parameterized to deploy a Jenkins instance and trigger a configurable amount of jobs. A cleanup mark (`scalecleanup`) is also included that deletes all jobs and then removes the Jenkins deployment.
Jobs can be created and run through `PYTEST_ARGS`:
```
$ PYTEST_ARGS="--masters=3 --jobs=10" ./test.sh -m scale jenkins
```
Environments can be cleaned up:
```
$ ./test.sh -m scalecleanup jenkins
```
> Tuneable jobs through pytest

- Dockerfile
- scripts/init.groovy.d/mesos-auth.groovy
- testing/jenkins.py
Use the init hook system of Jenkins to set the correct credentials for the Mesos Cloud when run on a strict DC/OS cluster.
> Add init script for mesos auth

- testing/jenkins.py
- tests/acceptance/test_jenkins.py
- tests/scale/test_load.py
- tests/scale/test_scale_utils.py
Create one marathon client and use that for all installations. This
is to help against flooding the service and to prevent changing the
`dcos` config numerous times per execution.
> Use one marathon connection

- Dockerfile
- universe/package.json
- Remove SHA256 verification checks.
- Update libmesos-bundle to 1.12 and DC/OS min version to 1.10.
> Fix CI failures.

- conftest.py
- testing/sdk_security.py
- tests/scale/test_load.py
Grant Admin Router access to `mom` and `jenkins-role` mesos roles.
JIRA: [DCOS-52220](https://jira.mesosphere.com/browse/DCOS-52220)
> Configure Admin-Router roles
